# Generated by Django 4.2 on 2025-04-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(max_length=20)),
                ('numberOfRooms', models.IntegerField()),
                ('fullName', models.CharField(max_length=200)),
                ('phoneNo', models.CharField(max_length=20)),
                ('creditCardType', models.CharField(max_length=20)),
                ('creditCard', models.CharField(max_length=20)),
                ('validThru', models.CharField(max_length=20)),
                ('CVC', models.CharField(max_length=20)),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('totalPrice', models.IntegerField()),
            ],
        ),
    ]
